### ISSUE TITLE
Update Maestro sensor cache whenever sensor in DB updates

### ISSUE THREAD

**Issue by iOiurson** [anthill/pheromon#42]
We have chosen to use `sim2sensor` as a memory cache on api's maestro client.
This implies to keep both this cache and the actual DB in line with each other.

**Comment by iOiurson** [comment]
I'm thinking about using the same process as in `databaseClientP.js`, but with `maestro`.
Once connected and operational, we would export the `maestro` client to the database direct functions, and use the `importSensors` maestro util function each time a db function is called.

Any thoughts on that @DavidBruant ?

**Comment by DavidBruant** [comment]
Things changed a lot since I last looked at it. Let's talk about this face to face for a complete answer, but quickly:

> We have chosen to use sim2sensor as a memory cache on api's maestro client.

Why? Does it matter to have it as cache, why not look up the DB each time? It doesn't seem that much performance critical.

> This implies to keep both this cache and the actual DB in line with each other.

Indeed.
"There are only two hard things in Computer Science: cache invalidation and naming things."
http://martinfowler.com/bliki/TwoHardThings.html

Either invalidate completely any time anything changes or adopt a more subtle policy (but these are harder to write right obviously).

**Comment by iOiurson** [comment]
I removed the cache in #48. Probably for the best :p
